### ISSUE TITLE
Error after new commit

### ISSUE THREAD

**Issue by xnetcat** [Ryzzzen/manaflux#12]
![image](https://user-images.githubusercontent.com/42355410/44298022-ce734b00-a2db-11e8-8e64-94ff35e1783a.png)

[commit](https://github.com/Ryzzzen/manaflux/commit/efd134df0a61005145568059b1199e62eb19d86e)

**Comment by thomas-cardon** [comment]
Hello, are you updated with the last commits?

**Comment by xnetcat** [comment]
![image](https://user-images.githubusercontent.com/42355410/44298591-231bc380-a2e6-11e8-8f6e-5b0656bf0635.png)

Yes, it's updated


To make sure I downloaded your source code and i had same result.

**Comment by thomas-cardon** [comment]
It's really weird, because when I force the translation module to use the polish language it works.. Try doing a `npm install` again, this is maybe because I've added a dependency for the crash reporter.

**Comment by xnetcat** [comment]
When i will be in home, I will try again.

I use npm install after every new commit

**Comment by thomas-cardon** [comment]
I removed unhandled rejections/errors event from the main process since I get them on my crash reporter and made the translation module more error-friendly in the last commits. Check if it works now!

**Comment by xnetcat** [comment]
Fixed <3
