### ISSUE TITLE
Runes editor: pages not updating (Champion Select)

### ISSUE THREAD

**Issue by xnetcat** [Ryzzzen/manaflux#13]
https://youtu.be/ovl58ur9XRg

Can't see runes in champion select, but later it's ok.

Sorry for so many issues but i want to help

**Comment by thomas-cardon** [comment]
I'm the one that should be sorry! I think it's a UI glitch, have you tried in-game? I think it's just the client's UI that can't keep up. I don't think I can fix that, but I'll check later.

**Comment by xnetcat** [comment]
Yes, it works in the game, but collection behaves like champion select ( maybe it was one time on my pc, u should check it in free time ), after restarting Client it works

**Comment by xnetcat** [comment]
Here is vid https://youtu.be/2Z8UrWXiLM0

**Comment by thomas-cardon** [comment]
Okay, yeah it took time for me to understand haha
Yeah it's an issue I've seen a long time ago, that I forgot to check. I'll check it tomorrow

**Comment by thomas-cardon** [comment]
Hey, so I checked a bit, there's no way for me to make the client see, or acknowledge the new runepages. The client would have to request the runes again, but I can't force it. The runes editor will probably always be like that and I can't do anything about it. Sorry!

**Comment by tuucan** [comment]
I think riot shoul know about this. If their API allows runes to change, then they need to provide a way to force an update on rune pages.

**Comment by thomas-cardon** [comment]
The thing is that it's not a public endpoint, that's private. The connection I made to their client is by reverse-engineering their client. They don't have any problem with it, but they won't make a new endpoint just for me either. Anyway I've added an option on the rework branch to choose the method you'd want Manaflux to use, either to update the runes or to delete then re-create them (which will "fix" in that case this issue).

**Comment by tuucan** [comment]
Oh ok, that should be convenient. Thanks.

**Comment by thomas-cardon** [comment]
Okay so I'm re-opening this issue since the fix that I thought was working is not. I removed the fix in the last version (1.5.4).

**Comment by thomas-cardon** [comment]
I reworked how perks are injected into the client on the master branch. Seems to fix the editor, it'd be good to have feedback if you have time!

**Comment by tuucan** [comment]
Doesn't seem to work for me, looks like the same as before (v2.0.3)

**Comment by thomas-cardon** [comment]
It's totally random and I don't think we can fix it, besides forcing the client to reload the editor by deleting a rune page and recreating it instead of updating it (that's basically the fix). The option is going to stay in the stable releases for those who doesn't have any issues with it, but for now League still doesn't allow us to reload the runes editor UI when needed.
