### ISSUE TITLE
ManaFlux doesn't load after "Path found"

### ISSUE THREAD

**Issue by rawora** [Ryzzzen/manaflux#14]
Hello, the program found my league path and I thought that it would work now. Still when I join the champ select and pick a champion, it wont show the icon / runes etc and act like it isn't connected to my client.

![image](https://user-images.githubusercontent.com/12943161/44304078-f30a0a00-a351-11e8-8549-bb11461a9674.png)

**console:**
![image](https://user-images.githubusercontent.com/12943161/44304084-1fbe2180-a352-11e8-9d23-0914c4ab196f.png)

**Comment by thomas-cardon** [comment]
Hello! When it is connected to your client, ManaFlux will say at the bottom "Waiting for champion select". It seems that it indeed found the path, but is blocking on something else.
- Can you try pressing the keys `Win+R`? It'll open a "Run" window.
- Then copy-paste in the box this command: `cmd.exe /k "%LOCALAPPDATA%\Programs\manaflux\ManaFlux.exe"`

It'll show you a second window, you can screenshot it or copy-paste it in code tags if you want. It might help me to find and fix the issue.

**Comment by rawora** [comment]
Hello,

when I opened ManaFlux today, it worked!

I think I needed to restart it a couple times, but now I have no problems. 

Thank you for your time.
