### ISSUE TITLE
Stuck at loading

### ISSUE THREAD

**Issue by Marly212** [Ryzzzen/manaflux#15]
So my Friend Downloaded the App and it Stuck in the Loading (Login If It is not Done already) Screen.
If he Picks a Champ nothing Changes in the App

![stuck screen](https://user-images.githubusercontent.com/42452096/44309119-0d7bcc00-a3c2-11e8-8e7a-5bd544ee1fc1.png)

I found the Command you wrote in another Issue and execute it.
![command](https://user-images.githubusercontent.com/42452096/44309131-3d2ad400-a3c2-11e8-8149-0c0b5e8af2b6.png)

I hope it will help you.

**Comment by thomas-cardon** [comment]
Hello! I'd like to know a few things first.
- The region you're on
- Was he connected?
- Did he start ManaFlux before or after League of Legends?
- Can you head into the console tab using `Mana.store.get('leaguePath')` and copy-paste here what it says?

**Comment by Marly212** [comment]
Hello, 
1.  He Plays on EUW just like me
2.  What do you mean by "Was he connected?"
3.  We tried both and it doesn't work either
4.  
![console](https://user-images.githubusercontent.com/42452096/44310096-132cde00-a3d1-11e8-9a8d-8a437481ad87.png)

**Comment by thomas-cardon** [comment]
What I meant was did he log into League of Legends? And also, was his League Client patching/updating?
I'm gonna check and try to fix the issue.

**Comment by Marly212** [comment]
We tried both when he was logged in and when he wasn't, And his League Client wasn't patching.

**Comment by thomas-cardon** [comment]
Hello! I'm gonna release a new version soon that'll allow me to catch more errors and issues, and that will save everything into log files. When it is released, I'll tell you how to upload the file here.

**Comment by thomas-cardon** [comment]
Hello! Try with the new update, I made multiple tries and fixed over twenty issues. You might need to reset the settings using the button in the settings. In case there's still an issue, open again this issue or open another if it's not related to this anymore.
