### ISSUE TITLE
Logs

### ISSUE THREAD

**Issue by xnetcat** [Ryzzzen/manaflux#16]
When a different language than English is in use , logs should not be in this language but in English for easier debugging
![logs](https://user-images.githubusercontent.com/42355410/44312275-e9d27900-a3f5-11e8-885f-a7eb164bf339.png)

**Comment by thomas-cardon** [comment]
True. I think that might be just the statuses tho. Anyway I'm releasing something to allow me easier debugging aswell too. I'm gonna ensure that everything else is in english.

**Comment by thomas-cardon** [comment]
I added the LoggingHandler class, along with some other improvements everywhere, to ensure the logs stay in english, even if it's for a status. The UI will still be translated according to your system language if available. See here: https://github.com/Ryzzzen/manaflux/commit/4b6a87adf6c4cc786922b520d2a5a508517ca2c6
