### ISSUE TITLE
Loading Problem

### ISSUE THREAD

**Issue by sch-28** [Ryzzzen/manaflux#2]
Hi,
The app is stuck in the "LOADING" status on the bottom right, don't know what to do :/

Here is my log:
```
Loading storage...
ui.js:63 [Localization] Loading value: menu-home
ui.js:63 [Localization] Loading value: menu-settings
ui.js:63 [Localization] Loading value: menu-update
ui.js:63 [Localization] Loading value: button-load-summoner-spells
ui.js:63 [Localization] Loading value: button-load-runes
ui.js:63 [Localization] Loading value: load-automatically
ui.js:63 [Localization] Loading value: summonerspells
ui.js:63 [Localization] Loading value: enable
ui.js:63 [Localization] Loading value: itemsets
ui.js:63 [Localization] Loading value: enable
ui.js:63 [Localization] Loading value: startup
ui.js:63 [Localization] Loading value: startup-windows
ui.js:63 [Localization] Loading value: taskbar
ui.js:63 [Localization] Loading value: champion-select-hide
ui.js:63 [Localization] Loading value: animations
ui.js:63 [Localization] Loading value: enable
ui.js:63 [Localization] Loading value: theme
ui.js:63 [Localization] Loading value: theme-default
ui.js:63 [Localization] Loading value: theme-forest
ui.js:63 [Localization] Loading value: theme-shurima-desert
2ui.js:63 [Localization] Loading value: color-red
ui.js:63 [Localization] Loading value: color-green
ui.js:63 [Localization] Loading value: color-purple
ui.js:63 [Localization] Loading value: color-gray
ui.js:63 [Localization] Loading value: update-available
ui.js:63 [Localization] Loading value: menu-update
ui.js:63 [Localization] Loading value: loading
ui.js:85 Loading value of loadRunesAutomatically to: true
ui.js:85 Loading value of enableSummonerSpells to: true
ui.js:85 Loading value of enableItemSets to: false
ui.js:85 Loading value of auto-start to: true
ui.js:85 Loading value of enableTrayIcon to: false
ui.js:85 Loading value of enableAnimations to: false
ui.js:93 Loading value of theme to: themes/forest-bg.png
```

**Comment by thomas-cardon** [comment]
Hello, I'm still pushing updates to fix things. It's stuck probably because It can't find League's client. I'm pushing an update that will probably fix this issue pretty soon.

**Comment by sch-28** [comment]
Oh ok, thank you for your reply! I am looking forward for the patch :)

**Comment by sch-28** [comment]
Sadly the patch did not work for me, it is still stuck in the loading status :/
Could it be because my LoL folder is on D:\ and not on C:\ ?

Edit:
I used the command `Mana.store.clear();` to reset the program, now the status is stuck on "PATH FOUND...". When i restart the program, while this status is active, it switches back to "LOADING" and stays like this.

**Comment by thomas-cardon** [comment]
I'm rolling out multiple patches, because I just found a issue where sometimes Windows chose to start PowerShell instead of cmd.exe, preventing ManaFlux from connecting to League. This version is v1.4.13, and it's coming soon. Sorry for that! I hope it'll resolve your issue.

**Comment by timowie** [comment]
I still have this issue. When I first start ManaFlux and LoL, it finds the correct folder (checked the logs) and keeps showing "League:Path Found" (maybe it freezes there? nothing happens afterwards). After I restart ManaFlux it keeps saying "Loading (Login if it is not done already)"
![looogs](https://user-images.githubusercontent.com/37001922/44274224-e8f8e600-a241-11e8-9cc7-ce1d9d3e3d2a.PNG)

**Comment by thomas-cardon** [comment]
I'm sorry, this issue is known and I'm working on it but it's kinda random, it seems that it happens when you have installed League of Legends somewhere else. Can you tell me where it is installed so I can give you the steps to try to solve this issue? e.g `C:\Riot Games\League of Legends\`

**Comment by xTheEc0** [comment]
Mines at `D:\Riot Games\League of Legends`

**Comment by thomas-cardon** [comment]
Try going back into the console and copy paste this: `Mana.store.set('leaguePath', 'D:\Riot Games\League of Legends\')`. Depending on people this may or may not work. I'm still working on it.

**Comment by xTheEc0** [comment]
Seems to have caught on.
One note - `\` needs to be escaped. 
So instead of `D:\Riot Games\\League of Legends\\` path needs to be `D:\\Riot Games\\League of Legends\\`

Thanks : )

**Comment by timowie** [comment]
Indeed it works with the command (when used with "\\\\" as sxTheEc0 described). My path is `S:/LeagueOfLegends`. Thanks for the quick help! Keep up the good work :)
