### ISSUE TITLE
Build a github page

### ISSUE THREAD

**Issue by recs182** [Ryzzzen/manaflux#21]
It would be easier for users to _interact_ with the software since not everyone is familiarized with Github.

**Comment by thomas-cardon** [comment]
I agree. I'll get on this when I've finished releasing the next update.

**Comment by recs182** [comment]
I could help to setup it if you want some help.

**Comment by thomas-cardon** [comment]
I just enabled GitHub pages on the master branch, If you have the time it'd be really cool yes! Thanks!

**Comment by recs182** [comment]
Ok, I never created one but I read about it and it should be easy... I'll try to improve [this](https://ryzzzen.github.io/manaflux/) when I get home.

**Comment by recs182** [comment]
I made a pull request with updated translation and a test to see with I'm in the correct path for the page.

**Comment by thomas-cardon** [comment]
I'm gonna check it out once I've finished reworking the foundations of the app!

**Comment by recs182** [comment]
I'll test it on a project that I have, it'll be better because I got how it works now so I don't to create a lot of pull requests.

I'll edit the page to include the direct download links and I'll saw if I can add a dynamic release notes.
