### ISSUE TITLE
UI not loading

### ISSUE THREAD

**Issue by anarionIv** [Ryzzzen/manaflux#22]
![mana](https://user-images.githubusercontent.com/37512325/44428912-25a44480-a596-11e8-848e-8aa10f7860d6.PNG)
That's what's happening right after installation.

Windows 10

**Comment by thomas-cardon** [comment]
There might be a second window. Can you see it ? It's saying that Manaflux isn't isn’t endorsed by Riot Games.

**Comment by anarionIv** [comment]
nope no 2nd window.

**Comment by thomas-cardon** [comment]
Press the Ctrl+Shift+I shortcut, and go into the Console Tab, then screenshot what it says

**Comment by thomas-cardon** [comment]
To my mind, I really think there's something behind that prevents you from loading the page. The page blocks loading only until you press OK on the consent window. When you do, it loads, and it doesn't bother you anymore (well, unless you reset your settings!). I know that loading is blocked because of the background of the app, it's only a color, which changes at the end of the loading.

**Comment by anarionIv** [comment]
![mana2](https://user-images.githubusercontent.com/37512325/44429521-09090c00-a598-11e8-9549-a5c05df1125f.PNG)

**Comment by thomas-cardon** [comment]
No, I meant the console tab. 
![image](https://user-images.githubusercontent.com/5779685/44429555-1b834580-a598-11e8-9b70-a36be25b0384.png)

**Comment by anarionIv** [comment]
![mana console](https://user-images.githubusercontent.com/37512325/44429750-d27fc100-a598-11e8-98fa-d06b21bb07c9.PNG)

**Comment by thomas-cardon** [comment]
Okay, so that's a translation problem. Can you tell me what language do you have on your PC?

**Comment by anarionIv** [comment]
german

**Comment by thomas-cardon** [comment]
Okay, so I found the issue. I'm gonna release a new update fixing it pretty sound. What I found is, that Manaflux hangs when it finds a language not translated, instead of falling back to english. I'll tell you when I've finished! Sorry for that!

**Comment by thomas-cardon** [comment]
Okay, here's [the release](https://github.com/Ryzzzen/manaflux/releases/tag/v1.5.2). It should fix your problems. If you have another issue (that is still related to this bug), feel free to open again this issue!
Commit fixing your issue in case you'd care: 38b97ebc1930d4b6f81937670b7d02e34f8353e4
