### ISSUE TITLE
App intercepts all ctrl + shift + i key inputs

### ISSUE THREAD

**Issue by WBittner** [Ryzzzen/manaflux#23]
Could you make it so when the app is hidden it doesn't intercept this key input? Or even better if the window is not focused. I cannot use this key input to open the dev tools in my browser when the app is running

**Comment by thomas-cardon** [comment]
That's something I didn't thought about, I'll do something about it for the next release!

**Comment by WBittner** [comment]
As of latest update, app still intercepts my ctrl + shift + i command, it just does nothing if the window is not in focus rather than letting the command do what it normally would (so my browsers console still can't be opened). I believe the issue is you are still registering a global shortcut - see docs here for non-global vs global: https://electronjs.org/docs/tutorial/keyboard-shortcuts.

**Comment by thomas-cardon** [comment]
Okay I just fixed this issue in the rework branch, see here: https://github.com/Ryzzzen/manaflux/commit/56487bcbcd8e7d32b6c807f00fa086d5839e2ebc.

I might release this fix with a minor update with other fixes, or it'll be available for the next major update.
Thanks a lot for your help!
