### ISSUE TITLE
Rune page creation

### ISSUE THREAD

**Issue by IanLulz** [Ryzzzen/manaflux#3]
Would it be possible to place the runes into a specified page? IE. I have a rune page that is designated for changing runes often. For champions with multiple suggested pages, you could prompt the user which one they'd like to use on the ManaFlux UI.

**Comment by thomas-cardon** [comment]
Hello. By default it uses as many slots as needed, for example if you only have two rune pages it will use both of them for Champion.GG. That's something I'm probably gonna add soon. Thanks for the idea!

**Comment by IanLulz** [comment]
Thanks for the response. Glad I could provide feedback! Loving ManaFlux so far :)

**Comment by rawora** [comment]
I think it would be very cool, if ManaFlux could show you maybe 2-3 Rune pages as recommendation (maybe the two most-used and/or best/highest-winrate rune pages) and you could click on one of them to "apply" them into your runepage. 

So it won't give you two runepages and you can choose right away, since you'll use only one anyways.

**Comment by thomas-cardon** [comment]
I probably can do it, since it already shows a button to load runes if you disable automatic runes loading. I'll think about it!

**Comment by rawora** [comment]
Thank you for your consideration. :)

**Comment by thomas-cardon** [comment]
Hey! So I added in the latest releases today an option in the settings to allow you to set a maximum number of pages you'd like Manaflux to change. If you put 1, it'll limit itself to the first page available. 

The feature you requested is not such a priority (seeing how much issues people are having for now!) but it can come in the next weeks or so if I have the time or if someone helps.

I'm gonna close the issue though, until I start working on it.
Thanks for your support!
