### ISSUE TITLE
Error start

### ISSUE THREAD

**Issue by AntoninHuaut** [Ryzzzen/manaflux#37]
Error when starting the program, last version, w10.
![87pw9xc](https://user-images.githubusercontent.com/1338257/44924497-be338500-ad4b-11e8-9a43-abb7a23af1c7.jpg)

**Comment by thomas-cardon** [comment]
Hello! I recommand you to get back to the latest stable version. The 1.6.0-ALPHA version was for testing the update module and I completely forgot to remove it once I had finished. The rework branch is very unstable for now. Sorry!
