### ISSUE TITLE
Rune Page is not Updating

### ISSUE THREAD

**Issue by Marly212** [Ryzzzen/manaflux#4]
I Installed the App and its working but it won't change my Runes in Champ Select.
![consolen tab](https://user-images.githubusercontent.com/42452096/44235434-d03cf180-a1a9-11e8-89c9-e8082512a0b0.png)

**Comment by thomas-cardon** [comment]
Hello! Can you expand the Errors you're seeing at the bottom (in red)? Just click the arrow before "StatusCodeError".

**Comment by thomas-cardon** [comment]
I may have found the error. I'm gonna upload a patch soon. You'll just have to click on the UPDATE glowing button when it shows on ManaFlux.
