### ISSUE TITLE
Stuck at loading

### ISSUE THREAD

**Issue by iSytrus** [Ryzzzen/manaflux#42]
Hi. Sorry for bad english.
The program is completely stuck at launch. The buttons do nothing, and i need to manually terminate it through Task Manager.
My client's language/region is RU if its matter.
Can you please take a look? Thank you.

![001](https://user-images.githubusercontent.com/12570015/46570238-c47bd900-c969-11e8-94c1-174c764a0094.png)
![002](https://user-images.githubusercontent.com/12570015/46570239-c47bd900-c969-11e8-99c1-f8a515d9754f.png)

**Comment by xnetcat** [comment]
Hi @iSytrus this is alpha version. Try [v 1.5.4](https://github.com/Ryzzzen/manaflux/releases/download/v1.5.4/manaflux-setup-1.5.4.exe) and tell if it works

**Comment by iSytrus** [comment]
>this is alpha version.

Oh, sorry, did not pay attention to it. The stable version works perfect, thank you.

**Comment by xnetcat** [comment]
Great. You can close this issue
