### ISSUE TITLE
Languages need to be updated

### ISSUE THREAD

**Issue by thomas-cardon** [Ryzzzen/manaflux#43]
Hello everyone, I have just merged the rework branch into the master branch, since we're pretty close to a stable release. However if someone has time, all languages need to be updated (except english).

### Languages that need an update
- **German** (DE)

### Languages added
- **Italian** (IT) - Thanks @LorisSecuro
- **Russian** (RU) - Thanks @iSytrus

### Languages updated
- **Portuguese brazilian** (PT-BR) - Thanks @recs182 
- **Polish** (PL) - Thanks @kko7
- **Spanish** (ES) - Thanks @rogama25
- **French** (FR)

> **Note**: It might be easier to just copy&paste the english file and then edit the values, since I also changed, added and removed a lot of keys.

@kko7 gave me this software, called [i18n-manager](https://github.com/gilmarsquinelato/i18n-manager), that might help you.

The languages folder is [here](https://github.com/Ryzzzen/manaflux/tree/master/objects/i18n/locales).

**Comment by LorisSecuro** [comment]
I could add the Italian translation if you are interested.

**Comment by thomas-cardon** [comment]
That's actually a good idea! If you have time, you simply have to create a **it.json** with the same keys as in **english.json**, and change the values. You can either upload it here, and I'll make a commit in the master branch, or you can clone and make a pull request.

**Comment by iSytrus** [comment]
Hi.
I just finished russian translation. Please add it if you don't mind. There might be a few mistakes, but I will fix them later if I find out how to do that :D
[ru.zip](https://github.com/Ryzzzen/manaflux/files/2475947/ru.zip)

**Comment by thomas-cardon** [comment]
> Hi.
> I just finished russian translation. Please add it if you don't mind. There might be a few mistakes, but I will fix them later if I find out how to do that :D
> [ru.zip](https://github.com/Ryzzzen/manaflux/files/2475947/ru.zip)

Thanks for your help! It'll be available for the next pre-release (v1.9.5)

**Comment by thomas-cardon** [comment]
I've added a tool inside Manaflux to help you find unused or missing lines for any language you want.
It looks like this:
![Manaflux language testing tool](https://cdn.discordapp.com/attachments/482182708454490122/501135305395666962/unknown.png)

I'm still trying to see if there's something good online that could help you to get better translations and faster, like Crowdin for example. Problem is, that I can't make Crowdin compatible with Electron for some reasons.
