### ISSUE TITLE
UI: replace navigation arrows by dots

### ISSUE THREAD

**Issue by iSytrus** [Ryzzzen/manaflux#57]
Advanced settings are now hidden until you find these two little arrows at the top left corner.
It may be better to use dots like these:

![001](https://user-images.githubusercontent.com/12570015/47133944-95dbf780-d2b3-11e8-9976-b4e9bd3c7686.png)

In my opinion, it becomes a little more obvious that there are additional settings here.

**Comment by thomas-cardon** [comment]
Hello! That's actually a great idea! It can even be used for other things that I'd like to implement later, such as statistics. I'll see what I can do this weekend!

**Comment by thomas-cardon** [comment]
![image](https://user-images.githubusercontent.com/5779685/47219043-f94a5000-d3ad-11e8-932b-fac2f81e0e1d.png)

My work here is done.
Commits:  <br>
>https://github.com/Ryzzzen/manaflux/commit/b6208bd84c942e341ecfb549bb788258b8abc4a4
> https://github.com/Ryzzzen/manaflux/commit/2e397b693614c831d1822c038f49dd1a614e0d72

Feel free to re-open this issue if you think of ways to improve the dots!
