### ISSUE TITLE
Identifier 'itemset' has already been declared

### ISSUE THREAD

**Issue by OrangeNote** [Ryzzzen/manaflux#6]
https://github.com/Ryzzzen/manaflux/blob/33a4a6e7ac5b9c2e24cf03b5b81c529d0261160b/objects/providers/LoLFlavor.js#L29-L32

You might want to change `let` to `var` or rename the variable.

**Comment by thomas-cardon** [comment]
Hello! Thanks for your help! I made a commit just now to fix this.
