### ISSUE TITLE
2.0 is out: known issues

### ISSUE THREAD

**Issue by thomas-cardon** [Ryzzzen/manaflux#61]
I just released the new stable release, If you find some issues please let us know here.

**Known issues**

- Manaflux can be launched multiple times
- Update button seems to not work in pre-releases/2.0 (Fixed in the next release!)

**Comment by thomas-cardon** [comment]
Item sets are not parsed correctly, preventing Manaflux from loading perks
> Can be fixed by disabling item sets. Might be fixed with the latest commits

**Comment by thomas-cardon** [comment]
There's currently another issue, that makes the runes change but not its name, so the data gets injected but sometimes for example if you play Irelia and you had played Pyke just before, the name will still be Pyke. This issue has already been fixed for the next release, but this issue doesn't prevent you from loading the runes.

**Comment by OskarPh** [comment]
Everything was working fine, now it's a lot of problems for no reason.
Runes not loading.
Downloading data takes a long time and runes weren't even loaded!

**Comment by thomas-cardon** [comment]
Sorry for your issues. A minor release is coming pretty soon with a lot of fixes.

**Comment by OskarPh** [comment]
Is there anyway to save to loaded runes as my own page?
And now it stopped working completely...

**Comment by thomas-cardon** [comment]
If you build the master branch you'd have some of the fixes I've already made that may fix your problems. You can also open an issue with your log files for me to see if I can do something. Maybe you should reset Manaflux or clear the cache.
