### ISSUE TITLE
Ordering of website ignored?

### ISSUE THREAD

**Issue by daicain** [Ryzzzen/manaflux#70]
I choose OP.GG as my top and main site to load runes from, it always load from LOG1

**Comment by thomas-cardon** [comment]
I need more information to help you.

**Version or branch**: V.X.X
**A screenshot**: in that case, your order
**The logs**: Go in Manaflux settings, open the logs folder, and upload here the file

**Comment by daicain** [comment]
Version or branch: v2.0.3
A screenshot: in that case, your order: https://i.imgur.com/XV5kttk.png
The logs: Go in Manaflux settings, open the logs folder, and upload here the file
`[Main] [log] [21:25:44] [ConnectionHandler] League of Legends connection data detected
[Main] [log] [21:25:44] [ConnectionHandler] Reading connection file
[Renderer] [log] [21:25:44] [Settings] Loading value of perks-max to: 2
[Renderer] [log] [21:25:44] [Settings] Loading value of champion-select-min-roles to: 2
[Renderer] [log] [21:25:44] [Settings] Loading value of summoner-spells-priority to: d
[Renderer] [log] [21:25:44] [Settings] Loading value of ui-background to: themes/default-bg.jpg
[Renderer] [log] [21:25:44] [Settings] Loading value of league-client-path to: C:\Riot Games\League of Legends\
[Renderer] [log] [21:25:44] [Settings] Loading value of perks-automatic-load to: undefined
[Main] [log] [21:25:44] [ConnectionHandler] Checking session...
[Renderer] [log] [21:25:44] [Settings] Loading value of summoner-spells to: undefined
[Renderer] [log] [21:25:44] [Settings] Loading value of item-sets-enable to: undefined
[Renderer] [log] [21:25:44] [Settings] Loading value of launch-at-startup to: false
[Renderer] [log] [21:25:44] [Settings] Loading value of tray-enable to: false
[Renderer] [log] [21:25:44] [Settings] Loading value of champion-select-lock to: undefined
[Renderer] [log] [21:25:44] [Settings] Loading value of ui-animations-enable to: false
[Renderer] [log] [21:25:44] [Settings] Loading value of ui-gradient to: true
[Renderer] [log] [21:25:44] [Settings] Loading value of ui-animations-smoke to: true
[Renderer] [log] [21:25:44] [Settings] Loading value of fixes-perks-editor to: true
[Renderer] [log] [21:25:44] [UI] [Custom Components] Loading bug-reports
[Main] [log] [21:25:44] [ConnectionHandler] Player is logged into League of Legends
[Renderer] [log] [21:25:44] [UI] [Custom Components] Loading hextech-background
[Renderer] [log] [21:25:44] [UI] [Custom Components] Loading perks-max
[Renderer] [log] [21:25:44] [UI] [Custom Components] Loading launch-at-startup
[Renderer] [log] [21:25:44] [UI] [Custom Components] Loading tray
[Renderer] [log] [21:25:44] [UI] [Custom Components] Loading ui-language-tester
[Renderer] [log] [21:25:45] [UI] [Custom Components] Loading ui-gradient
[Renderer] [log] [21:25:45] [UI] [Custom Components] Loading ui-animations-smoke
[Renderer] [log] [21:25:45] [UI] [Custom Components] Loading ui-background
[Renderer] [log] [21:25:45] [UI] Loading background: themes/default-bg.jpg
[Renderer] [log] [21:25:45] [UI] [Custom Components] Loading league-client-path
[Renderer] [log] [21:25:45] [UI] [Custom Components] Loading empty-cache
[Renderer] [log] [21:25:45] [UI] [Custom Components] Loading reset-settings
[Renderer] [log] [21:25:45] [UI] [Custom Components] Loading settings-logs-clear
[Renderer] [log] [21:25:45] [UI] [Custom Components] Loading settings-logs-open
[Renderer] [log] [21:25:45] [Localization] Loading value: ui-menu-home
[Renderer] [log] [21:25:45] [Localization] Loading value: ui-menu-settings
[Renderer] [log] [21:25:45] [Localization] Loading value: ui-menu-update
[Renderer] [log] [21:25:45] [Localization] Loading value: status-loading
[Renderer] [log] [21:25:45] [Localization] Loading value: summoner-spells-load-button
[Renderer] [log] [21:25:45] [Localization] Loading value: perks-load-button
[Renderer] [log] [21:25:45] [Localization] Loading value: category-perks
[Renderer] [log] [21:25:45] [Localization] Loading value: perks-max
[Renderer] [log] [21:25:45] [Localization] Loading value: perks-load-automatically
[Renderer] [log] [21:25:45] [Localization] Loading value: common-enable
[Renderer] [log] [21:25:45] [Localization] Loading value: category-misc
[Renderer] [log] [21:25:45] [Localization] Loading value: summoner-spells
[Renderer] [log] [21:25:45] [Localization] Loading value: common-enable
[Renderer] [log] [21:25:45] [Localization] Loading value: item-sets
[Renderer] [log] [21:25:45] [Localization] Loading value: common-enable
[Renderer] [log] [21:25:45] [Localization] Loading value: startup
[Renderer] [log] [21:25:45] [Localization] Loading value: startup-windows
[Renderer] [log] [21:25:45] [Localization] Loading value: taskbar
[Renderer] [log] [21:25:45] [Localization] Loading value: champion-select-hide
[Renderer] [log] [21:25:45] [Localization] Loading value: category-misc
[Renderer] [log] [21:25:45] [Localization] Loading value: champion-select-min-roles
[Renderer] [log] [21:25:45] [Localization] Loading value: champion-select-lock-button
[Renderer] [log] [21:25:45] [Localization] Loading value: common-enable
[Renderer] [log] [21:25:45] [Localization] Loading value: summoner-spells-priority
[Renderer] [log] [21:25:45] [Localization] Loading value: summoner-spells-priority-flash-d
[Renderer] [log] [21:25:45] [Localization] Loading value: summoner-spells-priority-flash-f
[Renderer] [log] [21:25:45] [Localization] Loading value: ui-language-tester
[Renderer] [log] [21:25:45] [Localization] Loading value: common-run
[Renderer] [log] [21:25:45] [Localization] Loading value: ui
[Renderer] [log] [21:25:45] [Localization] Loading value: ui-animations
[Renderer] [log] [21:25:45] [Localization] Loading value: common-enable
[Renderer] [log] [21:25:45] [Localization] Loading value: ui-gradient
[Renderer] [log] [21:25:45] [Localization] Loading value: common-enable
[Renderer] [log] [21:25:45] [Localization] Loading value: ui-animations-smoke
[Renderer] [log] [21:25:45] [Localization] Loading value: common-enable
[Renderer] [log] [21:25:45] [Localization] Loading value: ui-background
[Renderer] [log] [21:25:45] [Localization] Loading value: common-disabled
[Renderer] [log] [21:25:45] [Localization] Loading value: ui-background-default
[Renderer] [log] [21:25:45] [Localization] Loading value: ui-background-forest
[Renderer] [log] [21:25:45] [Localization] Loading value: ui-background-shurima-desert
[Renderer] [log] [21:25:45] [Localization] Loading value: ui-background-red_dark
[Renderer] [log] [21:25:45] [Localization] Loading value: ui-background-red
[Renderer] [log] [21:25:45] [Localization] Loading value: ui-background-green
[Renderer] [log] [21:25:45] [Localization] Loading value: ui-background-purple
[Renderer] [log] [21:25:45] [Localization] Loading value: ui-background-gray
[Renderer] [log] [21:25:45] [Localization] Loading value: ui-background-dark
[Renderer] [log] [21:25:45] [Localization] Loading value: ui-background-cloudy
[Renderer] [log] [21:25:45] [Localization] Loading value: ui-background-inspiration
[Renderer] [log] [21:25:45] [Localization] Loading value: ui-background-domination
[Renderer] [log] [21:25:45] [Localization] Loading value: ui-background-sorcery
[Renderer] [log] [21:25:45] [Localization] Loading value: ui-background-precision
[Renderer] [log] [21:25:45] [Localization] Loading value: category-advanced
[Renderer] [log] [21:25:45] [Localization] Loading value: league-client-path
[Renderer] [log] [21:25:45] [Localization] Loading value: empty-cache-settings-option
[Renderer] [log] [21:25:45] [Localization] Loading value: empty-cache-button
[Renderer] [log] [21:25:45] [Localization] Loading value: reset-settings-settings-option
[Renderer] [log] [21:25:45] [Localization] Loading value: reset-settings-button
[Renderer] [log] [21:25:45] [Localization] Loading value: settings-logs-clear
[Renderer] [log] [21:25:45] [Localization] Loading value: common-clear
[Renderer] [log] [21:25:45] [Localization] Loading value: settings-logs-open-folder
[Renderer] [log] [21:25:45] [Localization] Loading value: common-open
[Renderer] [log] [21:25:45] [Localization] Loading value: category-advanced
[Renderer] [log] [21:25:45] [Localization] Loading value: providers-order
[Renderer] [log] [21:25:45] [Localization] Loading value: fixes-perks-editor
[Renderer] [log] [21:25:45] [Localization] Loading value: common-enable
[Renderer] [log] [21:25:45] [Localization] Loading value: update-available
[Renderer] [log] [21:25:45] [Localization] Loading value: update-button-download
[Renderer] [log] [21:25:45] [GameAssetsProxy] Listening on port 3681
[Renderer] [log] [21:25:45] [Update] Not available
[Renderer] [dir] [21:26:14]
{"actions":[],"allowBattleBoost":true,"allowDuplicatePicks":false,"allowRerolling":true,"allowSkinSelection":true,"bans":{"myTeamBans":[],"numBans":0,"theirTeamBans":[]},"benchChampionIds":[],"benchEnabled":true,"boostableSkinCount":1,"chatDetails":{"chatRoomName":"8f0be16b-69ad-4b81-9be5-de35ae233c2e@champ-select.pvp.net","chatRoomPassword":null},"counter":4,"isSpectating":false,"localPlayerCellId":5,"myTeam":[{"assignedPosition":"","cellId":5,"championId":21,"championPickIntent":0,"playerType":"","selectedSkinId":21015,"spell1Id":4,"spell2Id":7,"summonerId":44143408,"team":2,"wardSkinId":7},{"assignedPosition":"","cellId":6,"championId":12,"championPickIntent":0,"playerType":"","selectedSkinId":12010,"spell1Id":32,"spell2Id":4,"summonerId":26158535,"team":2,"wardSkinId":-1},{"assignedPosition":"","cellId":7,"championId":117,"championPickIntent":0,"playerType":"","selectedSkinId":117000,"spell1Id":32,"spell2Id":4,"summonerId":41702737,"team":2,"wardSkinId":-1},{"assignedPosition":"","cellId":8,"championId":9,"championPickIntent":0,"playerType":"","selectedSkinId":9001,"spell1Id":4,"spell2Id":7,"summonerId":40440735,"team":2,"wardSkinId":-1},{"assignedPosition":"","cellId":9,"championId":429,"championPickIntent":0,"playerType":"","selectedSkinId":429000,"spell1Id":32,"spell2Id":4,"summonerId":23301443,"team":2,"wardSkinId":-1}],"rerollsRemaining":2,"theirTeam":[{"assignedPosition":"","cellId":0,"championId":0,"championPickIntent":0,"playerType":"","selectedSkinId":0,"spell1Id":0,"spell2Id":0,"summonerId":0,"team":1,"wardSkinId":-1},{"assignedPosition":"","cellId":1,"championId":0,"championPickIntent":0,"playerType":"","selectedSkinId":0,"spell1Id":0,"spell2Id":0,"summonerId":0,"team":1,"wardSkinId":-1},{"assignedPosition":"","cellId":2,"championId":0,"championPickIntent":0,"playerType":"","selectedSkinId":0,"spell1Id":0,"spell2Id":0,"summonerId":0,"team":1,"wardSkinId":-1},{"assignedPosition":"","cellId":3,"championId":0,"championPickIntent":0,"playerType":"","selectedSkinId":0,"spell1Id":0,"spell2Id":0,"summonerId":0,"team":1,"wardSkinId":-1},{"assignedPosition":"","cellId":4,"championId":0,"championPickIntent":0,"playerType":"","selectedSkinId":0,"spell1Id":0,"spell2Id":0,"summonerId":0,"team":1,"wardSkinId":-1}],"timer":{"adjustedTimeLeftInPhase":69996,"adjustedTimeLeftInPhaseInSec":69,"internalNowInEpochMs":1541366774187,"isInfinite":false,"phase":"FINALIZATION","timeLeftInPhase":69999,"timeLeftInPhaseInSec":69,"totalTimeInPhase":70000},"trades":[{"cellId":9,"id":8,"state":"AVAILABLE"},{"cellId":6,"id":9,"state":"AVAILABLE"},{"cellId":7,"id":10,"state":"INVALID"},{"cellId":8,"id":11,"state":"AVAILABLE"}]}
[Renderer] [log] [21:26:14] [ProviderHandler] Using METAsrc
[Renderer] [log] [21:26:14] [GameAssetsProxy] https://riot:5ZSxaRwiJlhNxo2LiLAmsQ@127.0.0.1:51744/lol-game-data/assets/v1/champion-icons/21.png
[Renderer] [log] [21:26:38] [ProviderHandler] Using League of Graphs
[Renderer] [log] [21:26:38] [ProviderHandler] [LOG] Gathering data (ARAM)
[Renderer] [log] [21:26:40] [ProviderHandler] Using LoLFlavor
[Renderer] [log] [21:26:40] [DataValidator] Copying required properties for Flu.x
[Renderer] [dir] [21:26:40]
{"roles":{"ARAM":{"perks":[{"selectedPerkIds":[8128,8126,8138,8135,8014,9111],"primaryStyleId":"8100","subStyleId":"8000","provider":"metasrc","name":"MSR1 Miss Fortune > ARAM"},{"selectedPerkIds":[8128,8126,8138,8106,9111,9104],"primaryStyleId":8100,"subStyleId":8000,"provider":"leagueofgraphs","name":"LOG2 Miss Fortune > ARAM"},{"selectedPerkIds":[8128,8126,8138,8106,8226,8234],"primaryStyleId":8100,"subStyleId":8200,"provider":"leagueofgraphs","name":"LOG3 Miss Fortune > ARAM"}],"summonerspells":[],"itemsets":[{"championKey":"MissFortune","file":"MFLUX_MissFortune_aram_metasrc_8.21_2.0.3.json","path":"C:\\Riot Games\\League of Legends\\Config\\Champions\\MissFortune\\Recommended\\MFLUX_MissFortune_aram_metasrc_8.21_2.0.3.json","_data":{"title":"MSR1 Miss Fortune > ARAM","type":"custom","map":"any","mode":"any","blocks":[{"items":{"1038":1,"2003":1,"3134":1},"recMath":false,"_type":{"i18n":"item-sets-block-starter"}},{"items":{"3006":1,"3031":1,"3087":1,"3142":1,"3147":1,"3508":1},"recMath":false,"_type":{"i18n":"item-sets-block-core-build-wr","arguments":["59.04%%"]}}],"priority":true,"provider":"metasrc"},"provider":"metasrc"},{"championKey":"MissFortune","file":"MFLUX_MissFortune_aram_lolflavor_8.21_2.0.3.json","path":"C:\\Riot Games\\League of Legends\\Config\\Champions\\MissFortune\\Recommended\\MFLUX_MissFortune_aram_lolflavor_8.21_2.0.3.json","_data":{"title":"LFV1 Miss Fortune > ARAM","type":"custom","map":"HA","mode":"any","blocks":[{"items":{"2003":1,"2031":1,"2032":1,"2033":1,"2047":1,"2055":1,"2138":1,"2139":1,"2140":1},"recMath":false,"_type":{"i18n":"item-sets-block-consumables"}},{"items":{"1028":1,"1036":1,"1038":1},"recMath":false,"_type":{"i18n":"item-sets-block-starter-skill-order","arguments":[["Q"," > ","W"," > ","E"]]}},{"items":{"1001":1,"3071":1,"3142":1,"3147":1},"recMath":false,"_type":{"i18n":"item-sets-block-core-build"}},{"items":{"3031":1,"3072":1,"3087":1,"3094":1,"3095":1,"3285":1,"3508":1},"recMath":false,"_type":{"i18n":"item-sets-block-endgame"}},{"items":{"3006":1,"3009":1,"3020":1,"3111":1},"recMath":false,"_type":{"i18n":"item-sets-block-boots"}},{"items":{"3033":1,"3035":1,"3036":1,"3136":1,"3151":1,"3812":1,"3814":1},"recMath":false,"_type":{"i18n":"item-sets-block-situational"}}],"priority":true,"provider":"lolflavor"},"provider":"lolflavor"}],"availablePositions":[],"statistics":{}}},"championId":21,"gameMode":"ARAM","gameVersion":"8.21","version":"2.0.3","region":"na"}
[Renderer] [log] [21:26:45] [UI] Opening logs folder
[Renderer] [log] [21:26:47] [Perks] Loading
`

**Comment by thomas-cardon** [comment]
When I was talking about uploading, I meant drag and drop the file not its content. I'll see what I can do!

**Comment by thomas-cardon** [comment]
Sorry for not answering for a long time, I completely forgot about that since I was focused on some bigger issues aswell. There's an update coming that should fix your issues, in the meantime I don't think I can do anything for you.

**Comment by daicain** [comment]
Thank you for answering!

**Comment by thomas-cardon** [comment]
The update has been released, re-open this issue if you still have problems with the order!
