### ISSUE TITLE
Internal error when entering ranked game

### ISSUE THREAD

**Issue by junhinhow** [Ryzzzen/manaflux#82]
![image](https://user-images.githubusercontent.com/7286017/51215660-07016a00-18f8-11e9-9a27-3147b52d4d82.png)

**Comment by xnetcat** [comment]
Hi @junhinhow ,

Can you send us logs and tell exactly what you did? You can find them in the folder by pressing the button in the settings. I will try to reproduce error. Do you still have this problem or it disappeared after restarting ?

You can contact me on Discord KKo7#5194

**Comment by thomas-cardon** [comment]
I'm closing the issue since there's no response.
