### ISSUE TITLE
Translation support

### ISSUE THREAD

**Issue by xnetcat** [Ryzzzen/manaflux#9]
Better support for translation after choosing a champion ?

![image](https://user-images.githubusercontent.com/42355410/44272567-87cf1380-a23d-11e8-9844-7614c5012e0b.png)

![image](https://user-images.githubusercontent.com/42355410/44272594-99b0b680-a23d-11e8-8909-ac20deb8aa55.png)

**Comment by thomas-cardon** [comment]
You can attach a JSON file here with the language you'd like to add, or create a pull request!

**Comment by xnetcat** [comment]
I mean I can't translate text after picking champion for example LOADED RUNES FOR POPPY (JG)..

**Comment by kko7** [comment]
I will make pull for JSON

**Comment by thomas-cardon** [comment]
This is because some texts aren't converted to the translation module I made yet. I'll update it to add the one you're asking.
